markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
auto: true
rdiscount:
  extensions: [smart]
title : Scale Horizontally
production_url : http://craigtracey.github.io/scalehorizontally.com
description: "A blog about building scalable, automated infrastructure"
disqus_shortname: scalehorizontally
#analytics:
#gauges: 50f2b533613f5d7c8000000c
author :
  name : Craig Tracey
  github : craigtracey
  twitter : craig_tracey
  email: craig@scalehorizontally.com
